### ISSUE TITLE
mainApi.py运行报错

### ISSUE THREAD

**Issue by xingfengsoft** [youzan/YZSpamFilter#6]
Traceback (most recent call last):
  File "mainApi.py", line 3, in <module>
    from filterApi import SpamFilter
  File "/home/liujie/YZSpamFilter/filterApi.py", line 8, in <module>
    from flask.ext.restful import abort, Resource
ImportError: No module named ext.restful

**Comment by xingfengsoft** [comment]
flask.ext.restful -> flask_restful
